### ISSUE TITLE
这个应用场景是啥

### ISSUE THREAD

**Issue by xiachaoxulu** [JuneAndGreen/doimg#1]
如果一个整buffer 都传输到浏览器端了，直接呈现就可以了嘛。  如果只有片段buffer 那么这个算法是不是也不起作用啊。  麻烦说下 应用场景

**Comment by JuneAndGreen** [comment]
@xiachaoxulu 这个库原本只是用于学习一些图片解析流程而建立的（配合一些博客文章的产出），亦可用于nodejs做简单图片解析。这个不是针对浏览器端，浏览器本身有健全的图片解析能力，不需要依赖额外的库。
