### ISSUE TITLE
png.decode()

### ISSUE THREAD

**Issue by TChengZ** [JuneAndGreen/doimg#2]
readme里面的使用png示例有如下代码
let pixels = png.decode(); // 像素数据
但看了png.js decode这个方法应该是有参数的，貌似这里readme有点小问题

**Comment by JuneAndGreen** [comment]
@TChengZ 那个参数是用于预解码用，在new的过程中会默认调用，所以不推荐自己调用。可参考代码：https://github.com/JuneAndGreen/doimg/blob/master/src/png.js#L24

**Comment by TChengZ** [comment]
ok
